"use client";

import React, { useState } from "react";
import { ChevronDown, HelpCircle } from "lucide-react";

interface FAQSectionProps {
  lang: "en" | "zh";
}

interface FAQItem {
  questionEn: string;
  questionZh: string;
  answerEn: string;
  answerZh: string;
}

const FAQ_LIST: FAQItem[] = [
  {
    questionEn: "When does OpenAI Codex reset usage limits?",
    questionZh: "OpenAI Codex 什么时候重置额度？",
    answerEn:
      "OpenAI Codex usage limits reset in two primary ways: 1) Rolling window resets occur automatically every 5 hours based on your tier; 2) Global/surprise resets or compensation drops occur periodically when major models roll out or service incidents happen (statistically every ~3.3 days based on past drops).",
    answerZh:
      "OpenAI Codex 的额度重置主要分为两种：1）个人滚动重置：根据您的订阅套餐，每 5 小时自动滚动恢复；2）全员全局重置/补偿卡：通常在重大模型更新（如 Astra 发布）或官方服务故障后由团队手动触发发放，根据历史数据统计平均约每 3.3 天一次。",
  },
  {
    questionEn: "How do banked reset cards work and do they expire?",
    questionZh: "什么是补发重置卡 (Banked Reset)？会过期吗？",
    answerEn:
      "Banked reset cards are on-demand manual resets credited to paid accounts (Plus, Pro, Business). You can trigger them anytime your quota is depleted. Note that banked cards typically expire after 30 days if unused.",
    answerZh:
      "重置卡 (Banked Reset) 是官方发放给付费会员（Plus、Pro、Team、Business）的随时支取额度卡。当您额度耗尽时可手动点击使用。请注意：未使用的重置卡通常具有 30 天有效期，过期会自动作废。",
  },
  {
    questionEn: "Do thinking tokens and prompt caching count against quota?",
    questionZh: "思考过程 (Thinking Tokens) 和缓存 (Prompt Cache) 扣额度吗？",
    answerEn:
      "Yes. Thinking tokens generated by reasoning models are counted toward your message quota. Prompt caching hits reduce latency but still consume baseline usage according to OpenAI's token policy.",
    answerZh:
      "是的。推理模型的思考 Token（Thinking Tokens）属于完整输出，会计入额度消耗；Prompt Cache 命中虽然能大幅提高响应速度并降低内部计算，但依然属于当次调用的计费额度范围之内。",
  },
  {
    questionEn: "How accurate is the WhenReset forecast percentage?",
    questionZh: "WhenReset 的重置预测百分比准确吗？如何计算的？",
    answerEn:
      "Our forecast is mathematical and data-driven: it tracks the median cadence (~3.3 days) across the last 10 official drops, combines cooldown decay, and factors in OpenAI incident reports and official team signals.",
    answerZh:
      "WhenReset 的预测是纯数学与数据驱动的：根据最近 10 次官方公开掉落的中位数周期（~3.3 天），结合冷却天数衰减模型、OpenAI 官方服务状态以及官方团队公开信号综合计算，绝不使用随机虚假数据。",
  },
];

export const FAQSection: React.FC<FAQSectionProps> = ({ lang }) => {
  const isZh = lang === "zh";
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  // Generate Schema.org FAQPage JSON-LD
  const schemaData = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQ_LIST.map((item) => ({
      "@type": "Question",
      name: isZh ? item.questionZh : item.questionEn,
      acceptedAnswer: {
        "@type": "Answer",
        text: isZh ? item.answerZh : item.answerEn,
      },
    })),
  };

  return (
    <div className="rounded-2xl glass-panel p-6 sm:p-8 mb-8 border border-white/10">
      {/* JSON-LD for Search Engines */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaData) }}
      />

      <div className="flex items-center space-x-2 text-xs font-semibold uppercase tracking-wider text-emerald-400 mb-2">
        <HelpCircle className="h-4 w-4" />
        <span>{isZh ? "额度与重置规则百科 (FAQ)" : "FREQUENTLY ASKED QUESTIONS"}</span>
      </div>
      <h2 className="text-lg font-bold text-white tracking-tight mb-6">
        {isZh
          ? "关于 Codex / Claude 重置与限额规则的一切"
          : "Everything you need to know about quota resets"}
      </h2>

      <div className="space-y-3">
        {FAQ_LIST.map((item, idx) => {
          const isOpen = openIndex === idx;
          return (
            <div
              key={idx}
              className="rounded-xl bg-white/[0.02] border border-white/[0.06] overflow-hidden transition-all"
            >
              <button
                onClick={() => setOpenIndex(isOpen ? null : idx)}
                className="w-full flex items-center justify-between p-4 text-left hover:bg-white/[0.03] transition-colors"
              >
                <span className="text-sm font-semibold text-slate-200">
                  {isZh ? item.questionZh : item.questionEn}
                </span>
                <ChevronDown
                  className={`h-4 w-4 text-slate-400 transition-transform duration-200 ${
                    isOpen ? "rotate-180 text-emerald-400" : ""
                  }`}
                />
              </button>
              {isOpen && (
                <div className="px-4 pb-4 pt-1 text-xs text-slate-300 leading-relaxed border-t border-white/[0.04]">
                  {isZh ? item.answerZh : item.answerEn}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
